# SPDX-License-Identifier: GPL-3.0-only WITH Commons-Clause-1.0
"""
TenantRepository — DAL for the tenants table.

Tenant creation (create) is bootstrap-level and does not require a caller-supplied
tenant_id — the new tenant doesn't exist yet. All other methods that read
tenant-scoped data call require_tenant() at the top before any DB interaction.

Usage::

    async with get_async_session_factory()() as session:
        repo = TenantRepository(session=session)
        tenant = await repo.create(name="Acme Corp")
        found  = await repo.get_by_id(tenant_id="<uuid>")
"""

import uuid
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from xeter.shared.dal.base import require_tenant
from xeter.shared.models import Tenant


class TenantRepository:
    """Repository for tenant-level CRUD operations."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(self, name: str) -> Tenant:
        """Insert a new tenant row and return the model instance.

        No tenant_id guard — this is bootstrap-level creation.
        The tenant_id is generated by the database (gen_random_uuid()).

        Args:
            name: Human-readable display name for the tenant.

        Returns:
            The freshly inserted Tenant ORM object with tenant_id populated.
        """
        tenant = Tenant(name=name)
        self._session.add(tenant)
        await self._session.flush()
        await self._session.refresh(tenant)
        return tenant

    async def get_by_id(self, tenant_id: str | None) -> Tenant | None:
        """Look up a tenant by primary key.

        Raises MissingTenantError before any DB interaction if tenant_id
        is absent or empty.

        Args:
            tenant_id: UUID string of the tenant to retrieve.

        Returns:
            The matching Tenant or None if not found.

        Raises:
            MissingTenantError: If tenant_id is None, empty, or whitespace-only.
        """
        require_tenant(tenant_id)
        result = await self._session.execute(
            select(Tenant).where(Tenant.tenant_id == uuid.UUID(str(tenant_id)))
        )
        return result.scalar_one_or_none()
